version: '3'

services: 

  api:
    build:
      context: ./api
    command: npm run start:watch
    links: 
      - mysql
    volumes:
      - ~/.intercard/data/
    environment:
            COMPOSE_PROJECT_NAME: intercard-docker
    logging:
      driver: 'json-file'
      options:
        max-size: '200k'
        max-file: '10'

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    expose:
      - '3306'
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    volumes:
        - ./cache/mysql:/var/lib/mysql
        - ./conf-mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_DATABASE=intercard
    restart: unless-stopped
    
